export const api = {
  uri: 'http://10.0.2.2:7000/api',
}

//actions
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const SET_TOKEN = 'SET_TOKEN'
export const SET_DEVICE = 'SET_DEVICES'
export const FETCHING_DEVICES = 'START_FETCHING_DEVICES'
export const START_FETCHING_MEASUREMENT = 'START_FETCHING_MEASUREMENT'
export const SET_MEASUREMENT = 'SET_MEASUREMENT'
export const START_FETCHING_ADD_DEVICES = 'START_FETCHING_ADD_DEVICES'

export const MQTT_CONNECTED = 'MQTT_CONNECTED'
export const MQTT_SUBSCRIBE = 'MQTT_SUBSCRIBE'
export const MQTT_MESSAGE = 'MQTT_MESSAGE'
export const MQTT_CONSUME = 'MQTT_CONSUME'
