export const api = {
  uri: 'http://10.0.2.2:7000/api',
}

//actions
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const SET_DEVICE = 'SET_DEVICES'
export const START_FETCHING_DEVICES = 'START_FETCHING_DEVICES'
export const START_FETCHING_MEASUREMENT = 'START_FETCHING_MEASUREMENT'
export const SET_MEASUREMENT = 'SET_MEASUREMENT'
